version: '3'

services:
  # Backend service
  java_app:
    container_name: java_app
    build:
      context: ./backend  # Specify the path to the directory containing the backend Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - java_db

  # Frontend service
  vue_frontend:
    container_name: vue_frontend
    build:
      context: ./frontend  # Specify the path to the directory containing the frontend Dockerfile
    ports:
      - 5173:5173  # Expose the port the Vue.js app runs on
    depends_on:
      - java_app

  # Database service
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}